version: "3.7"
services:
  comparecompanyinfo:
    build:
      context: .
      dockerfile: comparecompanyinfo/Dockerfile
    ports:
      - "33301:33301"
  ocr:
    build: 
      context: . 
      dockerfile: ocr/Dockerfile
    ports:
      - "33305:33305"
  sendemail:
    build:
      context: .
      dockerfile: sendemail/Dockerfile
    ports:
      - "33302:33302"
  checkcompanyinfo:
    build:
      context: .
      dockerfile: checkcompanyinfo/Dockerfile
    ports:
      - "33303:33303"
  dane_kup:
    build:
      context: .
      dockerfile: Dane_kup/Dockerfile
    ports:
      - "33306:33306"
  tag:
    build:
      context: .
      dockerfile: tag/Dockerfile
    ports:
      - "33307:33307"
  tax_cal:
    build:
      context: .
      dockerfile: tax_cal/Dockerfile
    ports:
      - "33308:33308"

  fileswebdepot:
    build:
      context: .
      dockerfile: FilesWebDepot/Dockerfile
    ports:
      - "33309:80"
    networks: 
      - local
    hostname: fileswebdepot1

  client:
    build:
      context: .
      dockerfile: client/Dockerfile
    ports:
      - "33304:33304"
    networks: 
      - local
    links:
      - comparecompanyinfo
      - sendemail
      - checkcompanyinfo
      - ocr
      - dane_kup
      - tag
      - tax_cal
      - fileswebdepot
    hostname: client1

networks:
  local:
    driver: bridge
